Aww_MVC/Controllers/CategoryController.cs
using AwwDTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AwwDomain;
using Aww_MVC.Models;

namespace Aww_MVC.Controllers
{
    public class CategoryController : Controller
    {
        // GET: CategoryController
        private Interactor _db;
        public CategoryController()
        {
            _db = new Interactor();
        }
        public ActionResult Index()
        {
            return View(_db.GetAllCategories().Select(c=>CategoryVM.GetVMFromDT(c)));
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        
        // GET: CategoryController/Create
        public ActionResult Create()
        {
            
            return View(new CategoryVM());
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            AwwCategoryDT cat = CategoryVM.GetDTFromCollection(collection);
            if (_db.AddCategoryToDb(cat))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(cat);
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Aww_MVC/Controllers/DatabaseController.cs
using Aww_MVC.Models;
using AwwDomain;
using AwwDTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Aww_MVC.Controllers
{
    public class DatabaseController : Controller
    {
        // GET: DatabaseController
        private Interactor _db;
        public DatabaseController()
        {
            _db = new Interactor();
        }
        public ActionResult Index()
        {
            IEnumerable<DbAwwVM> list = _db.GetAllAwwDTs().Select(x => DbAwwVM.GetVMFromDT(x));
            return View(list);
        }

        // GET: DatabaseController/Details/5
        public ActionResult Details(int id)
        {
            DbAwwVM aww = DbAwwVM.GetVMFromDT(_db.GetAwwDTById(id));
            return View(aww);
        }

        // GET: DatabaseController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DatabaseController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DatabaseController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DatabaseController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DatabaseController/Delete/5
        public ActionResult Delete(int id)
        {
            AwwDT aww = _db.GetAwwDTById(id);
            return View(aww);
        }

        // POST: DatabaseController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            if (_db.DeleteAwwDTById(id))
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

Aww_MVC/Views/Shared/_ApiUrlFormPartial.cshtml
@model APIFetchVM
<img height="200px" width="200px" src=@Model.ImageURL />

Aww_MVC/Views/Shared/_DbImageViewPartial.cshtml
@model DbAwwVM
<img height="200px" width="200px" src=@Model.ImageUrl />

Aww_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aww_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Aww_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aww_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Api View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Database" asp-action="Index">Image Database</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Aww_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>